[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_q4 = "DjLVzRa7F44qF4SY6KJDMNxAY93u1VH7iGV2Y6ERSt4F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
